# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yso_idrlhESq4Abs1lI-u82kEkf4rIrs
"""

import streamlit as st
from graph import graph

# -----------------------------
# Page Configuration
# -----------------------------

st.set_page_config(
    page_title="Agentic Technical Support Assistant",
    page_icon="🤖",
    layout="wide"
)

st.title("🤖 Agentic Technical Support Assistant")

st.write(
    "Ask technical questions about the Orion SmartHub X1 Pro."
)

# -----------------------------
# User Input
# -----------------------------

question = st.text_input(
    "Enter your technical question:"
)

# -----------------------------
# Submit Button
# -----------------------------

if st.button("Get Answer"):

    if not question.strip():
        st.warning("Please enter a question.")
        st.stop()

    initial_state = {
        "original_query": question,
        "optimized_query": "",
        "documents": [],
        "generation": "",
        "relevance_score": "",
        "hallucination_check": "",
        "loop_count": 0
    }

    with st.spinner("Generating answer..."):

        result = graph.invoke(initial_state)

    st.subheader("Answer")

    st.success(result["generation"])

    with st.expander("Agent Workflow"):

        st.write("### Optimized Query")
        st.write(result["optimized_query"])

        st.write("### Relevance Score")
        st.write(result["relevance_score"])

        st.write("### Hallucination Check")
        st.write(result["hallucination_check"])

        st.write("### Loop Count")
        st.write(result["loop_count"])