# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yso_idrlhESq4Abs1lI-u82kEkf4rIrs
"""

import streamlit as st
from graph import graph

# -----------------------------
# Page Configuration
# -----------------------------

st.set_page_config(
    page_title="Agentic Technical Support Assistant",
    page_icon="🤖",
    layout="wide"
)

st.title("🤖 Agentic Technical Support Assistant")

st.write(
    "Ask technical questions about the Orion SmartHub X1 Pro."
)

# -----------------------------
# User Input
# -----------------------------

question = st.text_input(
    "Enter your technical question:"
)

# -----------------------------
# Submit Button
# -----------------------------

if st.button("Get Answer"):

    if not question.strip():
        st.warning("Please enter a question.")
        st.stop()

    initial_state = {
        "original_query": question,
        "optimized_query": "",
        "documents": [],
        "generation": "",
        "relevance_score": "",
        "hallucination_check": "",
        "loop_count": 0,
    }

    workflow_steps = []
    final_state = initial_state

    with st.spinner("Generating answer..."):

        for step in graph.stream(initial_state):

            # Get node name
            node_name = list(step.keys())[0]
            workflow_steps.append(node_name)

            # Update final state with node output
            final_state.update(step[node_name])

    st.subheader("Answer")
    st.success(final_state["generation"])

    with st.expander("Agent Workflow", expanded=True):

        st.write("### Optimized Query")
        st.write(final_state["optimized_query"])

        st.write("### Relevance Score")
        st.write(final_state["relevance_score"])

        st.write("### Hallucination Check")
        st.write(final_state["hallucination_check"])

        st.write("### Loop Count")
        st.write(final_state["loop_count"])

        st.write("### Workflow Steps")

        STEP_NAMES = {
         "rewrite_query": "🔍 Query Rewrite Agent",
         "retrieve_documents": "📚 Document Retrieval Agent",
         "grade_documents": "✅ QA Validation Agent",
         "increment_loop": "🔄 Correction Loop Triggered",
         "web_search": "🌐 Web Search Agent",
         "generate_answer": "🤖 Answer Generation Agent",
         "hallucination_check": "🛡️ Hallucination Checker",
        }

        for i, step in enumerate(workflow_steps, start=1):
         st.success(f"{i}. {STEP_NAMES.get(step, step)}")