# -*- coding: utf-8 -*-
"""graph

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqq0YFpkD3k8cGQEPN27jRVCAyCarPZz
"""

import os
import uuid
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langchain_community.tools import DuckDuckGoSearchResults
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import START, StateGraph, END
from typing import TypedDict, List
from typing import Literal
from dotenv import load_dotenv
load_dotenv()
print("API key loaded:", os.getenv("OPENAI_API_KEY") is not None)
class RelevanceGrade(BaseModel):
    relevance_score: Literal["yes", "no"] = Field(
        description="Whether the retrieved documents are relevant."
    )

class HallucinationGrade(BaseModel):

    hallucination_check: Literal["passed", "failed"] = Field(
        description="Whether the generated answer is grounded in the provided documents."
    )

llm = ChatOpenAI(
    model="gpt-4.1-mini",
    temperature=0
)
structured_llm = llm.with_structured_output(RelevanceGrade)

from pathlib import Path
PDF_PATH = Path(__file__).parent / "orion_hub_manual.pdf"
loader = PyPDFLoader(str(PDF_PATH))
documents = loader.load()

text_splitter = RecursiveCharacterTextSplitter(

    chunk_size=500,
    chunk_overlap=100
)

chunks = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small"
)
collection_name = f"orion_{uuid.uuid4().hex}"
vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    collection_name=collection_name
)

retriever = vectorstore.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 5,
        "fetch_k": 10
    }
)

rewrite_prompt = ChatPromptTemplate.from_template("""
You are an expert Technical Support Specialist for the Orion SmartHub X1 Pro.

Your task is to rewrite customer questions into keyword-rich search queries for a vector database.

Instructions:
- Preserve the original intent.
- If the product name is missing, assume it is "Orion SmartHub X1 Pro".
- Replace vague words with technical terminology when appropriate.
- Include likely technical keywords that could appear in documentation.
- Do NOT answer the question.
- Return ONLY the rewritten search query.

Customer Question:
{question}
""")
query_rewriter = rewrite_prompt | llm
grade_prompt = ChatPromptTemplate.from_template("""
You are a QA Engineer responsible for validating document retrieval.

Your task is NOT to answer the user's question.

Determine whether the retrieved documents contain enough information
to answer the user's question.

Return ONLY:

"yes"
- if the retrieved documents contain sufficient information
to answer the user's question.

"no"
- if the retrieved documents only mention the topic,
- if they provide incomplete information,
- if they do not fully answer the user's question,
- or if additional information is needed.

User Question:
{question}

Retrieved Documents:
{documents}
""")

document_grader = grade_prompt | structured_llm
generate_prompt = ChatPromptTemplate.from_template("""
You are an expert Technical Support Engineer.

Answer the user's question using ONLY the information contained in the provided documents.

Instructions:
- Do NOT invent information.
- Do NOT make assumptions.
- If the documents do not contain enough information, clearly state that.
- Every statement in your answer must be directly supported by the retrieved documents.
   Do not infer troubleshooting steps.
   Do not invent recommendations.
- Use numbered steps whenever appropriate.

User Question:
{question}

Retrieved Documents:
{documents}
""")
generator = generate_prompt | llm
hallucination_llm = llm.with_structured_output(
    HallucinationGrade
)
hallucination_prompt = ChatPromptTemplate.from_template("""
You are a QA Engineer responsible for checking whether an AI-generated answer is supported by the provided documents.

Instructions:

- Compare the generated answer with the retrieved documents.
- Return "passed" if every important claim is supported by the documents.
- Return "failed" if the answer includes unsupported information or hallucinations.
- Do NOT judge writing quality.
- Judge ONLY factual grounding.

Retrieved Documents:
{documents}

Generated Answer:
{generation}
""")
hallucination_checker = (
    hallucination_prompt
    | hallucination_llm
)
search_tool = DuckDuckGoSearchResults(
    num_results=3
)

def rewrite_query(state):
    """
    Support Specialist Agent:
    Rewrites the user's query into an optimized search query.
    """

    response = query_rewriter.invoke(
        {"question": state["original_query"]}
    )

    return {
        "optimized_query": response.content
    }

def retrieve_documents(state):
    results = retriever.invoke(
        state["optimized_query"]
    )

    return {
        "documents": results
    }

def grade_documents(state):
    """
    QA Engineer Agent

    Checks whether the retrieved documents
    are relevant enough to answer the question.
    """

    documents = "\n\n".join(
        [doc.page_content for doc in state["documents"]]
    )

    result = document_grader.invoke(
        {
            "question": state["optimized_query"],
            "documents": documents,
        }
    )

    return {
        "relevance_score": result.relevance_score
    }

def web_search(state):
    print("\n========== WEB SEARCH NODE EXECUTED ==========\n")

    web_results = search_tool.invoke(state["optimized_query"])

    print("WEB RESULTS:")
    print(web_results)

    web_document = Document(
        page_content=str(web_results),
        metadata={"source": "web_search"}
    )

    return {
        "documents": [web_document]
    }
def generate_answer(state):
    """
    Support Specialist Agent

    Generates the final technical response
    using the retrieved documents.
    """

    documents = "\n\n".join(
        [doc.page_content for doc in state["documents"]]
    )

    response = generator.invoke(
        {
            "question": state["original_query"],
            "documents": documents,
        }
    )

    return {
        "generation": response.content
    }

def hallucination_check(state):
    """
    QA Engineer Agent

    Checks whether the generated answer
    is grounded in the retrieved documents.
    """

    documents = "\n\n".join(
        [doc.page_content for doc in state["documents"]]
    )

    result = hallucination_checker.invoke(
        {
            "documents": documents,
            "generation": state["generation"],
        }
    )

    return {
        "hallucination_check": result.hallucination_check
    }
def route_after_rewrite(state):
    """
    First pass:
        rewrite -> retrieve

    Retry:
        rewrite -> web search
    """

    if state["loop_count"] == 0:
        return "retrieve"

    return "web"

def route_after_grading(state):

    if state["relevance_score"] == "yes":
        return "generate"

    return "retry"

def route_after_hallucination(state):

    if state["hallucination_check"] == "passed":
        return "end"

    if state["loop_count"] >= 2:
        return "end"

    return "retry"

def increment_loop(state):
    """
    Increment retry counter.
    """

    return {
        "loop_count": state.get("loop_count", 0) + 1
    }

# Define GraphState
class GraphState(TypedDict):
    original_query: str
    optimized_query: str
    documents: List[Document]
    generation: str
    relevance_score: str
    hallucination_check: str
    loop_count: int

# Initialize builder
builder = StateGraph(GraphState)

# Add nodes
builder.add_node(
    "rewrite_query",
    rewrite_query
)
builder.add_node(
    "retrieve_documents",
    retrieve_documents
)
builder.add_node(
    "grade_documents",
    grade_documents
)
builder.add_node(
    "web_search",
    web_search
)
builder.add_node(
    "generate_answer",
    generate_answer
)
builder.add_node(
    "hallucination_check",
    hallucination_check
)
builder.add_node(
    "increment_loop",
    increment_loop
)

# Add edges
builder.add_edge(
    START,
    "rewrite_query"
)

builder.add_conditional_edges(
    "rewrite_query",
    route_after_rewrite,
    {
        "retrieve": "retrieve_documents",
        "web": "web_search",
    }
)

builder.add_edge(
    "retrieve_documents",
    "grade_documents"
)

builder.add_conditional_edges(
    "grade_documents",
    route_after_grading,
    {
        "generate": "generate_answer",
        "retry": "increment_loop",
    }
)

builder.add_edge(
    "increment_loop",
    "rewrite_query"
)

builder.add_edge(
    "web_search",
    "generate_answer"
)

builder.add_edge(
    "generate_answer",
    "hallucination_check"
)

builder.add_conditional_edges(
    "hallucination_check",
    route_after_hallucination,
    {
        "end": END,
        "retry": "increment_loop"
    }
)
def build_graph():
    return builder.compile()

graph = build_graph()